---
kind: pipeline
name: default

clone:
  disable: true

workspace:
  base: /workspace
  path: src/github.com/presslabs/controller-util

steps:
- name: git
  pull: default
  image: plugins/git
  settings:
    depth: 0
    tags: true

- name: dependencies
  image: quay.io/presslabs/bfc:0.12
  pull: always
  commands:
  - make dependencies

- name: int
  image: quay.io/presslabs/bfc:0.12
  commands:
  - make lint

- name: test
  image: quay.io/presslabs/bfc:0.12
  commands:
  - make test
