workspace:
  base: /go
  path: src/github.com/presslabs/controller-util

pipeline:
  dependencies:
    image: golang:1.13
    environment:
      - GO111MODULE=on
    commands:
      - make dependencies

  lint:
    image: golang:1.13
    environment:
      - GO111MODULE=on
    commands:
      - make lint

  test:
    image: golang:1.13
    environment:
      - GO111MODULE=on
    commands:
      - make test
