---
kind: pipeline
name: default

clone:
  disable: true

workspace:
  base: /workspace
  path: src/github.com/presslabs/controller-util

steps:
- name: git
  pull: default
  image: plugins/git
  settings:
    depth: 0
    tags: true

- name: dependencies
  image: presslabs/build:v1.1.0
  pull: always
  commands:
  - make build.tools

- name: lint
  image: presslabs/build:v1.1.0
  commands:
  - make lint

- name: test
  image: presslabs/build:v1.1.0
  commands:
  - make test

trigger:
  ref:
    exclude:
    - refs/heads/dependabot/**

---
kind: signature
hmac: f55df7a519243e9a5e52b55fb2ec90ea65d2f21c3a79f46c617c56c4255d02c8

...
