version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - iface
    - importas
    - inamedparam
    - interfacebloat
    - intrange
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testifylint
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl
    - zerologlint
  disable:
    - exhaustruct
    - gochecknoglobals
    - godox
    - gomoddirectives
    - ireturn
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck
  settings:
    cyclop:
      max-complexity: 10
    dupl:
      threshold: 400
    gocyclo:
      min-complexity: 10
    lll:
      line-length: 170
      tab-width: 4
  exclusions:
    generated: lax
    rules:
      - linters:
          - staticcheck
        text: ST1000
      - linters:
          - revive
        text: 'package-comments: should have a package comment'
      - linters:
          - revive
        text:  'avoid package names that conflict with Go standard library package names'
      - linters:
          - staticcheck
        path: (.*)_test\.go
        text: 'QF1008: could remove embedded field "ObjectMeta" from selector'
      - linters:
          - staticcheck
        path: (.*)_test\.go
        text: 'QF1008: could remove embedded field "VolumeSource" from selector'
      - linters:
          - depguard
        text: not allowed from list 'Main'
      - linters:
          - revive
        path: (.*)_test\.go
        text: should not use dot imports
      - path: (.+)\.go$
        text: 'G104: Errors unhandled'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
